### ISSUE TITLE
Страница для построения графов

### ISSUE THREAD

**Issue by missingdays** [OSLL/jabba_web_frontend#1]

**Comment by missingdays** [comment]
Отправил pull request #2 

Добавил страницу для построения `include` и `call` графов с параметрами.

### Steps to reproduce
1. Установить необходимые зависимости
```
pip install -r requirements.txt
```

2. Запустить web сервер
```
python3 run.py
```

3. Переходим на страницу `http://127.0.0.1:5000/graphs`, выполняем различные сценарии построения графов.

3.1 Сценарий 1
-  repository - https://github.com/mariadb-corporation/maxscale-jenkins-jobs
- yaml root - maxscale_jobs
- graph type - include graph
- files - maxscale_jobs/include/ci_url.yaml
- rank directrion - up down
- add legend - true

Должен отобразиться Include Graph из двух узлов с легендой

3.2 Сценарий 2
-  repository - https://github.com/mariadb-corporation/maxscale-jenkins-jobs
- yaml root - maxscale_jobs
- graph type - call graph
- call parameters - same-node node-parameters
- call display - text
- files - maxscale_jobs/build.yaml maxscale_jobs/build_all.yaml
- rank directrion - left right
- add legend - false

Должен отобразиться Call Graph с двумя root красными узлами без легенды

**Comment by zmm** [comment]
﻿На первом сценарии вот такое появилось в консоли после нажатия кнопки Plot ()

favicon.ico Failed to load resource: the server responded with a status of 404 (NOT FOUND)
api/graphs?repository=https%3A%2F%2Fgithub.com%2Fmariadb-corporation%2Fmaxs…ue&call_display=text&call_parameters=maxscale_jobs%2Finclude%2Fci_url.yaml Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)

**Comment by missingdays** [comment]
Обновил версию Jabba, после установки
```
pip3 install -r requirements.txt
```
должно исправиться.
