### ISSUE TITLE
Индикация процесса загрузки графа/анализа и прочих долгих обращений к бакенду

### ISSUE THREAD

**Issue by zmm** [OSLL/jabba_web_frontend#15]
Необходимо после нажатия на кнопку Plot показать либо прогресс бар либо иной контрол для отображения того, что сайт не завис и работа идет

**Comment by missingdays** [comment]
Иконка загрузки реализована в [этом коммите](https://github.com/OSLL/jabba_web_frontend/commit/a0d62484f248a73dfebd9a75a87b38a92e87bdb9)
Я в pull request не сделал об этом заметку, поскольку считал, что это не важная фича.
