### ISSUE TITLE
Задание ветки/коммита/тега в репозитории, для которых ведется анализ

### ISSUE THREAD

**Issue by zmm** [OSLL/jabba_web_frontend#18]

**Comment by missingdays** [comment]
Отправил pull request #25 

Добавил возможность задания ветки/коммита/тега, которые будут анализироваться.

### Steps to reproduce
1. Запустить сервер
```
python3 run.py
```

2. Зайти по ссылке `http://127.0.0.1:5001/analysis`

Заполнить форму

- repository - https://github.com/mariadb-corporation/maxscale-jenkins-jobs
- checkout target - master
- yaml root - maxscale_jobs
- synonyms - {same-node, node-parameters}
- analysis functiions - выбрать все 4
- depends on - maxscale_jobs/include/slave.yaml
- missing call parameters - same-node

Убедиться, что анализ сработал.

3. Зайти по ссылке `http://127.0.0.1:5001/graph`

Заполнить форму

- repository - https://github.com/mariadb-corporation/maxscale-jenkins-jobs
- checkout target - master
- yaml root - maxscale_jobs
- graph type - call graph
- call parameters - same-node
- call display - text
- files - maxscale_jobs/build_all.yaml

Убедиться, что граф построен.

4. Изменить checkout target на старый коммит

- repository - https://github.com/mariadb-corporation/maxscale-jenkins-jobs
- checkout target - b9b5a137882fa
- yaml root - maxscale_jobs
- graph type - call graph
- call parameters - same-node
- call display - text
- files - maxscale_jobs/build_all.yaml

Убедиться, что граф отличается от графа, построенного на шаге 3.
