### ISSUE TITLE
Хинты и описания для полей ввода - подсказки по форматам

### ISSUE THREAD

**Issue by zmm** [OSLL/jabba_web_frontend#19]

**Comment by missingdays** [comment]
Отправил pull request #26 

Добавил пример заполнения формы анализа и построения графов со всеми полями.

### Steps to reproduce

1. Запустить сервер
```
python3 run.py
```

2. Перейти по ссылке `http://127.0.0.1:5001/analysis`

Нажать кнопку `Fill In Example`. Нажать OK. Нажать кнопку `Analyze`.

Убедиться, что все поля заполнены и выведены результаты анализа.

3. Перейти по ссылке `http://127.0.0.1:5001/graphs`

Нажать кнопку `Fill In Example`. Нажать OK. Нажать кнопку `Plot`.

Убедиться, что все поля заполнены и построен граф.
