### ISSUE TITLE
Подсветка результатов анализа

### ISSUE THREAD

**Issue by zmm** [OSLL/jabba_web_frontend#21]
Все ок - зеленый, есть ошибки красный, по возможности пишем в заголовке блока результатов сколько ошибок/замечаний.

**Comment by missingdays** [comment]
Отправил pull request #23 

Добавил цвет и количество ошибок в результаты анализа. Добавил сортировку результатов, чтобы первыми показывались результаты, в которых есть ошибки.

### Steps to reproduce
1. Запустить сервер
```
python3 run.py
```

2. Зайти по ссылке `http://127.0.0.1:5001/analysis`

Заполнить форму

- repository - https://github.com/mariadb-corporation/maxscale-jenkins-jobs
- yaml root - maxscale_jobs
- synonyms - {same-node, node-parameters}
- analysis functiions - выбрать все 4
- depends on - maxscale_jobs/include/slave.yaml
- missing call parameters - same-node

Убедиться, что сначала показываются результаты с ошибками, что они подсвечены красным, и что показывается количество ошибок в них.
