### ISSUE TITLE
"Сворачиваемость" результатов анализа

### ISSUE THREAD

**Issue by zmm** [OSLL/jabba_web_frontend#22]
Для удобства просмотра у блоков с результатом анализа они должны иметь кнопку "Свернуть".

**Comment by missingdays** [comment]
Отправил pull request #24

Добавил возможность разворачивать и сворачивать результаты анализа. По умолчанию результаты показываются свернутыми.

### Steps to reproduce
1. Запустить сервер
```
python3 run.py
```

2. Зайти по ссылке `http://127.0.0.1:5001/analysis`

Заполнить форму

- repository - https://github.com/mariadb-corporation/maxscale-jenkins-jobs
- yaml root - maxscale_jobs
- synonyms - {same-node, node-parameters}
- analysis functiions - выбрать все 4
- depends on - maxscale_jobs/include/slave.yaml
- missing call parameters - same-node

Убедиться, что результаты можно сворачивать и разворачивать.
